add-bounds = 'minor'
allow-insecure-host = []
cache-dir = '.uv_cache'
cache-keys = [{ file = 'pyproject.toml' }]
#:null: check-url = ''
compile-bytecode = true
#:null=#cores: concurrent-builds = inf
concurrent-downloads = 100
#:null=#cores: concurrent-installs = inf
config-settings = { }
config-settings-package = { }
dependency-metadata = []
#:null: exclude-newer = '0000-00-00T00:00:00Z'
exclude-newer-package = { }
extra-build-dependencies = { }
extra-build-variables = { }
extra-index-url = []
find-links = []
fork-strategy = 'requires-python'
index-strategy = 'first-index'
index-url = 'https://pypi.org/simple'
keyring-provider = 'subprocess'
link-mode = 'hardlink'
native-tls = false
no-binary = false
no-binary-package = []
no-build = false
no-build-isolation = false
no-build-isolation-package = []
no-build-package = []
no-cache = false
no-index = false
no-sources = false
offline = false
prerelease = 'if-necessary-or-explicit'
preview = false
publish-url = 'https://upload.pypi.org/legacy/'
#:null: pypy-install-mirror = 'https://downloads.python.org/pypy'
python-downloads = 'automatic'
#:null: python-downloads-json-url = '.uv_cache/python_downloads.json'
#:null: python-install-mirror = 'https://github.com/astral-sh/python-build-standalone'
python-preference = 'managed'
reinstall = false
reinstall-package = []
required-version = '~=0.9.5'
resolution = 'highest'
trusted-publishing = 'automatic'
upgrade = false
upgrade-package = []


[pip]
all-extras = false
allow-empty-requirements = true
annotation-style = 'split'
break-system-packages = false
compile-bytecode = true
config-settings = { }
config-settings-package = { }
#:null: custom-compile-command = ''
dependency-metadata = []
emit-build-options = false
emit-find-links = false
emit-index-annotation = false
emit-index-url = false
emit-marker-expression = false
#:null: exclude-newer = '0000-00-00T00:00:00Z'
exclude-newer-package = { }
extra = []
extra-build-dependencies = { }
extra-build-variables = { }
extra-index-url = []
find-links = []
fork-strategy = 'requires-python'
generate-hashes = true
group = []
index-strategy = 'first-index'
index-url = 'https://pypi.org/simple'
keyring-provider = 'subprocess'
link-mode = 'hardlink'
no-annotate = false
no-binary = []
no-build = false
no-build-isolation = false
no-build-isolation-package = []
no-deps = false
no-emit-package = []
no-extra = []
no-header = false
no-index = false
no-sources = false
no-strip-extras = false
no-strip-markers = false
only-binary = []
output-file = 'requirements.txt'
#:null: prefix = '.venv'
prerelease = 'if-necessary-or-explicit'
#:null: python = 'python3.12'
#:null: python-platform = ''
python-version = '3.12'
reinstall = false
reinstall-package = []
require-hashes = false
resolution = 'highest'
strict = true
system = false
#:null: target = '.venv/site-packages'
torch-backend = 'auto'
universal = false
upgrade = false
upgrade-package = []
verify-hashes = true
