builtins = ['_']
cache-dir = '.ruff_cache'
exclude = [
    '.git',
    '.pyenv', '.venv', 'venv',
    '.idea', '.vscode',
    '__pypackages__', '__pycache__',
    '.pytest_cache', '.ruff_cache',
    'build', 'dist',
    '.uv_cache'
]
extend = 'pyproject.toml'
extend-exclude = []
extend-include = []
fix = true
fix-only = true
force-exclude = false
include = [
    '*.py', '*.pyi', '*.pyw', '*.ipynb',
    '**/pyproject.toml', 'ruff.toml', 'uv.toml',
]
indent-width = 4
line-length = 120
namespace-packages = []
output-format = 'full'
preview = false
required-version = '~=0.14.2'
respect-gitignore = true
show-fixes = true
src = ['backend']
#:pyproject imported: target-version = 'py312'
unsafe-fixes = true

[per-file-target-version]
#:null:


[analyze]
detect-string-imports = true
direction = 'dependencies'
exclude = []
preview = false
string-imports-min-dots = 2

[analyze.include-dependencies]
#:null:


[format]
docstring-code-format = true
docstring-code-line-length = 120
exclude = []
indent-style = 'space'
line-ending = 'lf'
preview = false
quote-style = 'single'
skip-magic-trailing-comma = false


[lint]
allowed-confusables = []
dummy-variable-rgx = '^$'  #:none:
exclude = []
explicit-preview-rules = false
extend-fixable = []
#:deprecated: extend-ignore = []
extend-safe-fixes = []
extend-select = []
extend-unsafe-fixes = []
external = []
fixable = ['ALL']
future-annotations = false
ignore = ['D']
#:deprecated: ignore-init-module-imports = true
logger-objects = []
preview = false
select = ['ALL']
task-tags = ['TODO', 'FIXME', 'XXX']
typing-extensions = false
typing-modules = []
unfixable = []

[lint.extend-per-file-ignores]
#:null:

[lint.per-file-ignores]
#:null:


[lint.flake8-annotations]
allow-star-arg-any = false
ignore-fully-untyped = false
mypy-init-return = false
suppress-dummy-args = false
suppress-none-returning = false


[lint.flake8-bandit]
allowed-markup-calls = []
check-typed-exception = false
extend-markup-names = []
hardcoded-tmp-directory = ['/tmp', '/var/tmp', '/dev/shm']
hardcoded-tmp-directory-extend = []


[lint.flake8-boolean-trap]
extend-allowed-calls = []


[lint.flake8-bugbear]
extend-immutable-calls = []


[lint.flake8-builtins]
allowed-modules = []
#:deprecated: builtins-allowed-modules = []
#:deprecated: builtins-ignorelist = []
#:deprecated: builtins-strict-checking = false
ignorelist = []
strict-checking = false


[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = false


[lint.flake8-copyright]
#:null: author = 'author'
#:null: min-file-size = 0
#:null: notice-rgx = '(?i)Copyright\s+((?:\(C\)|Â©)\s+)?\d{4}((-|,\s)\d{4})*'


[lint.flake8-errmsg]
max-string-length = 0


[lint.flake8-gettext]
extend-function-names = []
function-names = ['_', 'gettext', 'ngettext']


[lint.flake8-implicit-str-concat]
allow-multiline = true


[lint.flake8-import-conventions]
banned-from = []

[lint.flake8-import-conventions.aliases]
#:null:

[lint.flake8-import-conventions.banned-aliases]
#:null:

[lint.flake8-import-conventions.extend-aliases]
#:null:


[lint.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false
parametrize-names-type = 'tuple'
parametrize-values-row-type = 'tuple'
parametrize-values-type = 'tuple'
raises-extend-require-match-for = []
raises-require-match-for = [
    'BaseException', 'Exception',
    'ValueError', 'OSError', 'IOError',
    'EnvironmentError', 'socket.error',
]
warns-extend-require-match-for = []
warns-require-match-for = ['Warning', 'UserWarning', 'DeprecationWarning']



[lint.flake8-quotes]
avoid-escape = true
docstring-quotes = 'double'
inline-quotes = 'single'
multiline-quotes = 'single'


[lint.flake8-self]
extend-ignore-names = []
ignore-names = []


[lint.flake8-tidy-imports]
ban-relative-imports = 'parents'
banned-module-level-imports = []

[lint.flake8-tidy-imports.banned-api]
#:null:


[lint.flake8-type-checking]
exempt-modules = ['typing', 'typing_extensions']
quote-annotations = false
runtime-evaluated-base-classes = []
runtime-evaluated-decorators = []
strict = false


[lint.flake8-unused-arguments]
ignore-variadic-names = false


[lint.isort]
case-sensitive = true
classes = []
combine-as-imports = true
constants = []
default-section = 'third-party'
detect-same-package = true
extra-standard-library = []
force-single-line = false
force-sort-within-sections = false
force-to-top = []
force-wrap-aliases = true
forced-separate = []
from-first = false
known-first-party = []
known-local-folder = []
known-third-party = []
length-sort = false
length-sort-straight = false
lines-after-imports = 2
lines-between-types = 0
no-lines-before = []
no-sections = false
order-by-type = true
relative-imports-order = 'closest-to-furthest'
required-imports = ['from __future__ import annotations']
section-order = ['future', 'standard-library', 'third-party', 'first-party', 'local-folder']
single-line-exclusions = []
split-on-trailing-comma = false
variables = []

[lint.isort.sections]
#:null:


[lint.mccabe]
max-complexity = 10


[lint.pep8-naming]
classmethod-decorators = []
extend-ignore-names = []
ignore-names = []
staticmethod-decorators = []


[lint.pycodestyle]
ignore-overlong-task-comments =false
max-doc-length = 120
max-line-length = 120


[lint.pydoclint]
ignore-one-line-docstrings = false


[lint.pydocstyle]
convention = 'pep257'
ignore-decorators = []
ignore-var-parameters = false
property-decorators = []


[lint.pyflakes]
allowed-unused-imports = []
extend-generics = []


[lint.pylint]
allow-dunder-method-names = []
allow-magic-value-types = []
max-args = 5
max-bool-expr = 5
max-branches = 10
max-locals = 15
max-nested-blocks = 5
max-positional-args = 5
max-public-methods = 20
max-returns = 5
max-statements = 50


[lint.pyupgrade]
keep-runtime-typing = false


[lint.ruff]
#:deprecated: allowed-markup-calls = []
#:deprecated: extend-markup-names = []
parenthesize-tuple-in-subscript = false
